package TreeFam::Model::CatalystTreeFamDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'TreeFamDB',
    
    connect_info => {
        dsn => 
		#'dbi:mysql:database=treefam_homology_67x;host=localhost;port=3306', user => 'root', password => '123'
'dbi:mysql:treefam_homology_67hmm;host=web-mei-treefam;port=3365',user => 'treefam_admin',password => $ENV{TFADMIN_PSW},
    }
);

=head1 NAME

TreeFam::Model::CatalystTreeFamDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<TreeFam>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<TreeFamDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Fabian Schreiber

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
